apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: {{ .Values.project_name }}-latest
    owner: roman
    description: django_app_skillfactory_diplom
spec:
  replicas: 1
  selector:
    matchLabels:
      project: {{ .Values.project_name }}-latest
  template:
    metadata:
      labels:
        project: {{ .Values.project_name }}-latest
        owner: roman
        description: django_app_skillfactory_diplom_pod
    spec:
      hostname: app
      containers:
        - name: app
          image: satdarovroman/django-app:latest
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: "localhost"
            - name: DB_NAME
              value: "tutorial-dev"
            - name: DB_USER
              value: "vinhle"
            - name: DB_PASS
              value: "password"
          command: ["/bin/sh"]
          args: ["-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"]
        - name: db
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tutorial-dev"
            - name: POSTGRES_USER
              value: "vinhle"
            - name: POSTGRES_PASSWORD
              value: "password"
