version: '3.7'

services:

  elasticsearch:
    image: elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=$ELK_PASS
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always

  kibana:
    container_name: kibana
    image: kibana:7.5.0
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELK_PASS
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always