- name: install CNI
  hosts: kub_master
  gather_facts: false
  become: false
  become_user: "root"
  become_method: "sudo"


  tasks:

    - name: apply calico
      shell:
        cmd: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml"
